# -------------------------------------------------------------------
# Input Tables & Sourcing
# -------------------------------------------------------------------
assemblies_tsv: "assemblies_spa_single.tsv"
output_dir: "results"

# -------------------------------------------------------------------
# Assembly Configuration
# -------------------------------------------------------------------
# Options: "spades" (metaSPAdes) or "megahit"
assembler: "spades"