# -------------------------------------------------------------------
# Input Tables & Sourcing
# -------------------------------------------------------------------
assemblies_tsv: "assemblies_toy.tsv"
output_dir: "results_toy"

# -------------------------------------------------------------------
# Assembly Configuration
# -------------------------------------------------------------------
# Options: "spades" (metaSPAdes) or "megahit"
assembler: "spades"
